version: '3'
services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: vm-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command: 
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    expose:
      - 9100
    networks:
      - monitorer

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: vm-nginx-exporter
    restart: unless-stopped
    command:
      - '--nginx.scrape-uri=http://bangunsite:8000/api/server/nginx'
    expose:
      - 9113
    networks:
      - monitorer

  prometheus:
    image: prom/prometheus:latest
    container_name: vm-prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - node-exporter
      - nginx-exporter
    expose:
      - 9090
    networks:
      - monitorer

  grafana:
    image: grafana/grafana
    container_name: vm-grafana
    user: '0'
    restart: unless-stopped
    # entrypoint: sh -c "sed -i 's/472/1000/g' /etc/passwd && sed -i 's/472/1000/g' /etc/group && /run.sh"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/dashboard.json
    volumes:
      - ./data/grafana/lib:/var/lib/grafana:rw
      - ./config/grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
      - ./config/grafana/nginx.json:/var/lib/grafana/dashboards/nginx.json
      - ./config/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/dashboard.yml
    ports:
     - 127.0.0.1:3000:3000
    networks:
      - monitorer

networks:
  monitorer:
    external: true
    name: vm