global:
  scrape_interval:     5s
  evaluation_interval: 5s
  external_labels:
      monitor: 'VM-stats'
rule_files:
  # - "alert.rules"
  # - "first.rules"
  # - "second.rules"
scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090', 'vm-node-exporter:9100']
  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['vm-nginx-exporter:9113']